server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: ${ROUTE_USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/users/**, /api/auth/**
            
        - id: demand-service
          uri: ${ROUTE_DEMAND_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/demands/**
            
        - id: property-service
          uri: ${ROUTE_PROPERTY_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/properties/**

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Placeholder 256-bit hex secret
