server:
  port: 8082

spring:
  application:
    name: demand-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/demand_db}
  redis:
    host: ${SPRING_DATA_REDIS_HOST:localhost}
    port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html

gemini:
  api:
    key: ${GOOGLE_GEMINI_API_KEY:placeholder-key}

user-service:
  url: ${ROUTE_USER_SERVICE_URI:http://localhost:8081}
