server:
  port: 8083

spring:
  application:
    name: property-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/property_db}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
